### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dimitrisnl** [dimitrisnl/next-authentication-tutorial#1]
- [ ] Add email registration (next-auth, nodemailer)
- [ ] Add GraphQL server (Apollo-micro-server, nexus)
- [ ] Add fetching hook example
- [ ] Update folder structure src/frontend, src/backend etc
